### ISSUE TITLE
When opening a file from GUI and closing it, sometimes it VLC start from GUI again until computer reboot.

### ISSUE THREAD

**Issue by jtagcat** [flathub/org.videolan.VLC#90] opened 2019-12-13 23:53 UTC
Related #47 
Fedora 31
I always close windows with `Alt`+`f4`.

When opening and closing video files through Nautilus, sometimes (when purposely testing, then usually after 3-6 times) VLC doesn't open again.
Killing it doesn't help. It won't open by open from Gnome Activities search, it won't open when trying to open a file.

Interestingly, regardless of whether you kill vlc, it always opens from the CLI with `flatpak run org.videolan.VLC`.

Running with `-vvv` after an incident:
```
$ flatpak run org.videolan.VLC -vvv
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[000055a2ab869080] main libvlc debug: VLC media player - 3.0.8 Vetinari
[000055a2ab869080] main libvlc debug: Copyright © 1996-2019 the VideoLAN team
[000055a2ab869080] main libvlc debug: revision 3.0.8-0-gf350b6b5a7
[000055a2ab869080] main libvlc debug: configured with ./configure  '--prefix=/app' 'BUILDCC=/usr/bin/gcc -std=gnu99' '--disable-a52' 'CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed' 'CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
[000055a2ab869080] main libvlc debug: searching plug-in modules
[000055a2ab869080] main libvlc debug: loading plugins cache file /app/lib/vlc/plugins/plugins.dat
[000055a2ab869080] main libvlc debug: recursively browsing `/app/lib/vlc/plugins'
[000055a2ab869080] main libvlc debug: plug-ins loaded: 506 modules
[000055a2ab869080] main libvlc debug: opening config file (/home/jc/.var/app/org.videolan.VLC/config/vlc/vlcrc)
[000055a2ab8693d0] main logger debug: looking for logger module matching "any": 4 candidates
[000055a2ab8693d0] main logger debug: using logger module "console"
[000055a2ab869080] main libvlc debug: translation test: code is "C"
[000055a2ab8fe3c0] main keystore debug: looking for keystore module matching "memory": 4 candidates
[000055a2ab8fe3c0] main keystore debug: using keystore module "memory"
[000055a2ab869080] main libvlc debug: CPU has capabilities MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 FPU 
[000055a2ab9038a0] main input debug: Creating an input for 'Media Library'
[000055a2ab9038a0] main input debug: Input is a meta file: disabling unneeded options
[000055a2ab9038a0] main input debug: using timeshift granularity of 50 MiB
[000055a2ab9038a0] main input debug: using default timeshift path
[000055a2ab9038a0] main input debug: `file/directory:///home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf' gives access `file' demux `directory' path `/home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf'
[000055a2ab8fe7d0] main input source debug: creating demux: access='file' demux='directory' location='/home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf' file='/home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf'
[000055a2ab8feed0] main demux debug: looking for access_demux module matching "file": 19 candidates
[000055a2ab8feed0] main demux debug: no access_demux modules matched
[000055a2ab914eb0] main stream debug: creating access: file:///home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf
[000055a2ab914eb0] main stream debug:  (path: /home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf)
[000055a2ab914eb0] main stream debug: looking for access module matching "file": 27 candidates
[000055a2ab914eb0] main stream debug: using access module "filesystem"
[000055a2ab915e00] main stream debug: looking for stream_filter module matching "prefetch,cache_read": 26 candidates
[000055a2ab915e00] cache_read stream debug: Using stream method for AStream*
[000055a2ab915e00] cache_read stream debug: starting pre-buffering
[000055a2ab915e00] cache_read stream debug: received first data after 0 ms
[000055a2ab915e00] cache_read stream debug: pre-buffering done 296 bytes in 0s - 8759 KiB/s
[000055a2ab915e00] main stream debug: using stream_filter module "cache_read"
[000055a2ab916d70] main stream debug: looking for stream_filter module matching "any": 26 candidates
[000055a2ab916d70] playlist stream debug: using XSPF playlist reader
[000055a2ab916d70] main stream debug: using stream_filter module "playlist"
[000055a2ab916d70] main stream debug: stream filter added to 0x55a2ab915e00
[000055a2ab91a190] main stream debug: looking for stream_filter module matching "any": 26 candidates
[000055a2ab91a190] main stream debug: no stream_filter modules matched
[000055a2ab8fec20] main stream_directory debug: looking for stream_directory module matching "any": 1 candidates
[000055a2ab8fec20] main stream_directory debug: no stream_directory modules matched
[000055a2ab8fe7d0] main input source debug: attachment of directory-extractor failed for file:///home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf
[000055a2ab91a190] main stream debug: looking for stream_filter module matching "record": 26 candidates
[000055a2ab91a190] main stream debug: using stream_filter module "record"
[000055a2ab8fe7d0] main input source debug: creating demux: access='file' demux='directory' location='/home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf' file='/home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf'
[000055a2ab8feed0] main demux debug: looking for demux module matching "directory": 53 candidates
[000055a2ab8feed0] main demux debug: using demux module "directory"
[000055a2ab91e2f0] main demux meta debug: looking for meta reader module matching "any": 2 candidates
[000055a2ab91e2f0] lua demux meta debug: Trying Lua scripts in /home/jc/.var/app/org.videolan.VLC/data/vlc/lua/meta/reader
[000055a2ab91e2f0] lua demux meta debug: Trying Lua scripts in /app/lib/vlc/lua/meta/reader
[000055a2ab91e2f0] lua demux meta debug: Trying Lua playlist script /app/lib/vlc/lua/meta/reader/filename.luac
[000055a2ab91e2f0] lua demux meta debug: Trying Lua scripts in /app/share/vlc/lua/meta/reader
[000055a2ab91e2f0] main demux meta debug: no meta reader modules matched
[000055a2ab9038a0] main input debug: `file/directory:///home/jc/.var/app/org.videolan.VLC/data/vlc/ml.xspf' successfully opened
[000055a2ab8ffa50] main xml reader debug: looking for xml reader module matching "any": 1 candidates
[000055a2ab8ffa50] main xml reader debug: using xml reader module "xml"
[000055a2ab9038a0] main input debug: EOF reached
[000055a2ab8feed0] main demux debug: removing module "directory"
[000055a2ab91a190] main stream debug: removing module "record"
[000055a2ab916d70] main stream debug: removing module "playlist"
[000055a2ab915e00] main stream debug: removing module "cache_read"
[000055a2ab914eb0] main stream debug: removing module "filesystem"
[000055a2ab901470] main playlist debug: creating audio output
[000055a2ab937650] main audio output debug: looking for audio output module matching "any": 5 candidates
[000055a2ab937650] vlcpulse audio output debug: using library version 12.2.0
[000055a2ab937650] vlcpulse audio output debug:  (compiled with version 12.2.0, protocol 32)
[000055a2ab937650] vlcpulse audio output debug: connected locally to unix:/run/user/1000/pulse/native as client #32
[000055a2ab937650] vlcpulse audio output debug: using protocol 32, server protocol 33
[000055a2ab937650] pulse audio output debug: adding sink 0: alsa_output.pci-0000_00_1f.3.analog-stereo (Built-in Audio Analog Stereo)
[000055a2ab937650] main audio output debug: using audio output module "pulse"
[000055a2ab901470] main playlist debug: keeping audio output
[000055a2ab9433f0] main interface debug: looking for interface module matching "dbus,none": 18 candidates
[000055a2ab9433f0] main interface debug: using interface module "dbus"
[000055a2ab947460] main interface debug: looking for interface module matching "hotkeys,none": 18 candidates
[000055a2ab947460] main interface debug: using interface module "hotkeys"
[000055a2ab947de0] main interface debug: looking for interface module matching "globalhotkeys,none": 18 candidates
[000055a2ab947de0] main interface debug: using interface module "xcb_hotkeys"
[000055a2ab869080] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[000055a2ab948d60] main interface debug: looking for interface module matching "any": 18 candidates
Gtk-Message: 01:52:55.610: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:52:55.610: Failed to load module "pk-gtk-module"
Gtk-Message: 01:52:55.611: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:52:55.611: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[00007f2d00106d80] main generic debug: looking for extension module matching "any": 1 candidates
[00007f2d00106d80] lua generic debug: Opening Lua Extension module
[00007f2d00106d80] lua generic debug: Trying Lua scripts in /home/jc/.var/app/org.videolan.VLC/data/vlc/lua/extensions
[00007f2d00106d80] lua generic debug: Trying Lua scripts in /app/lib/vlc/lua/extensions
[00007f2d00106d80] lua generic debug: Trying Lua playlist script /app/lib/vlc/lua/extensions/VLSub.luac
[00007f2d00106d80] lua generic debug: Scanning Lua script /app/lib/vlc/lua/extensions/VLSub.luac
[00007f2d00106d80] lua generic debug: Script /app/lib/vlc/lua/extensions/VLSub.luac has the following capability flags: 0x5
[00007f2d00106d80] lua generic debug: Trying Lua scripts in /app/share/vlc/lua/extensions
[00007f2d00106d80] main generic debug: using extension module "lua"
[000055a2ab948d60] main interface debug: using interface module "qt"
[000055a2ab901470] main playlist: playlist is empty
[000055a2ab901470] main playlist debug: nothing to play
```

**Comment by jtagcat** [comment] 2019-12-15 22:04
Additional info: ~40min of video in one file, after closing vlc, audio remained for ~2 seconds.
Running from CLI opens it, but that doesn't reset the behaviour (still doesn't open from Nautilus). Out of what I tested, only restarting the computer helps.
Tested: Can't open from Thunar as well.

**Comment by MatMaul** [comment] 2019-12-19 10:29
Regarding different behavior between CLI and Nautilus it's probably related to the options of VLC regarding that.
When you say kill did you use -9 and have you checked that the process is still running after doing so ? If it is not running anymore can you check that you don't have some flatpak related process running ?
It's probably VLC not closing properly, but a kill -9 should work so that's weird.

**Comment by jtagcat** [comment] 2019-12-19 16:48
VLC does not respond to polite requests to end the process.
flatpak-session-helper does.

Ending flatpak-session-helper AND killing vlc.bin works.

**Comment by Unrud** [comment] 2019-12-19 19:29
I can reproduce the issue when starting VLC from CLI with a video file ``flatpak run org.videolan.VLC video_file.webm`` and pressing Alt+F4. The window closes but the process keeps running.

The likelihood of the problem appearing seems to depend on the video file being played. With some files VLC hangs almost every time and with other files I can't reproduce the problem.

I don't know what the common factor between the files causing the problem is, I've tested files with the same codecs and similar file sizes but get different results.

When running VLC with ``-vvv`` the problem appears very rarely with files that previously triggered the problem almost every time. This looks like a race condition.

The debug output when running with ``-vvv`` just stops shortly after closing the VLC window and the program hangs:

```
=> Closing window
[000055abb9c11080] main libvlc debug: exiting
[000055abb9c11080] main libvlc debug: exiting
[000055abb9c11080] main libvlc debug: removing all interfaces
[000055abb9cfdd70] main interface debug: removing module "qt"
[000055abb9cb2620] main playlist debug: deactivating the playlist
[000055abb9cb2620] main playlist debug: incoming request - stopping current input
[vp9 @ 0x7f3798c765c0] get_buffer() failed
[vp9 @ 0x7f3798c765c0] thread_get_buffer() failed
[00007f3798c5a630] packetizer_avparser packetizer debug: CPU flags: 0x000fd3db
[vp9 @ 0x7f3798ca3200] get_buffer() failed
[vp9 @ 0x7f3798ca3200] thread_get_buffer() failed
[000055abb9ceab30] pulse audio output debug: underflow
=> Output just stops here and program hangs.
```

Until the program hangs the debug output is practically identical to a error-free run.

> Ending flatpak-session-helper AND killing vlc.bin works.

Just run ``flatpak kill org.videolan.VLC``.

**Comment by MatMaul** [comment] 2019-12-20 10:39
Does it look specific to VP9 files ? or are you able to reproduce with a MP4 H264 file ? I am trying to know if the failure is more related to the vp9 error message I can see here, or the pulse audio one.
Once we found out we should have a look to VLC bug tracker because this is most probably not specific to Flatpak version.

**Comment by MatMaul** [comment] 2019-12-20 13:02
Also if you have a sample that triggers that a lot more often than others it would be nice to host it somewhere (even privately) so we can do more tests.

**Comment by Unrud** [comment] 2019-12-20 21:00
The common factor between the videos that trigger the issue seems to be the framerate:

  * 30 FPS: No issues.
  * 60 FPS: Issue appears sometimes; Issue appears often when VLC is closed shortly after the video starts.
  * 120 FPS: Issue always appears.

Further observations:

  * Issue only appears with OpenGl video output.
  * When I switch my laptop from Intel to Nvidia graphics, I can no longer reproduce the problem.
  * I can't reproduce the problem with the host's version of VLC. (Ubuntu 18.04)

> Does it look specific to VP9 files ? or are you able to reproduce with a MP4 H264 file ?

I can reproduce the issue with VP9 and H264 files.

> I am trying to know if the failure is more related to the vp9 error message I can see here, or the pulse audio one.

The messages are normal, they also appear on error-free runs. I can even disable audio output in VLC and the problem still appears.

> Also if you have a sample that triggers that a lot more often than others it would be nice to host it somewhere (even privately) so we can do more tests.

Every video with a high framerate seems to work.

**Comment by jtagcat** [comment] 2019-12-21 06:38
I can confirm the observations to make sense, I'm on intel-only graphics and struggle to play 4k 30fps (barely), pretty much any 60fps (even outside of vlc).

**Comment by MatMaul** [comment] 2019-12-21 11:29
Indeed I have no trouble reproducing with a 60fps video.
I can also reproduce with the rpmfusion package, it's definitively a VLC bug.
HW decoding seems to not impact this. Looks like a race condition in the OpenGL output.
Unfortunately I can't reproduce anymore if I use gdb :(
I'll open a bug on VLC trac when I have more time, feel free to do so and post a link if you have some free time before me.

**Comment by MatMaul** [comment] 2019-12-21 22:48
Ok so after refreshing a bit my gdb skills I found out that we are actually hitting this bug:
https://gitlab.freedesktop.org/xorg/lib/libxcb/issues/38
It could also be a bug in SIG handling of VLC:
https://stackoverflow.com/questions/25165794/random-libx11-hangs

**Comment by MatMaul** [comment] 2019-12-21 22:50
Here are the stacktraces relevant to the lockup:
https://pastebin.com/6bTwun0e

**Comment by glaubersm** [comment] 2020-08-17 02:28
mesa driver bug
https://gitlab.freedesktop.org/mesa/mesa/-/issues/116

**Comment by MatMaul** [comment] 2021-11-28 22:53
Closing this, upstream bugs exist and there is not much we can do.

**Closed by MatMaul** 2021-11-28 22:53 UTC
