### ISSUE TITLE
VLC exits after  flashing a title with Privacy and Network Access Policy in Ubuntu 16.04 32-bit

### ISSUE THREAD

**Issue by trappedinspacetime** [flathub/org.videolan.VLC#6] opened 2017-10-01 11:45 UTC
First of all thank you for developing **flatpak** environment and adding `vlc` to repo. 
I installed vlc with `flatpak install --user flathub org.videolan.VLC` command.
When I tried to run it like `flatpak run org.videolan.VLC`, it exits immediately after a gui flashes a title with "Privacy and Network Access Policy" then it disappears. I searched for it on the net, some say that it's a bug related to vlc when you launch it first time, and suggested a workaround by launching it like 

     flatpak run org.videolan.VLC --no-qt-privacy-ask
 That way suppresses the dialog, however `vlc` still keeps exiting. 
I hope you help me.
Regards.
Kenn.

**Comment by cosimoc** [comment] 2017-10-01 16:59
I can't reproduce this; the very first time the app starts up, I can see that window but it does not flash and when I close it, the app is running fine.

Are there any other messages on the terminal after the application exits?

**Comment by kensully** [comment] 2017-10-01 19:23
@cosimoc thank you for responding. I am on Ubuntu 16.04 32 bit platform. 
Here is the output of terminal:

```
~$ flatpak run  org.videolan.VLC 
VLC media player 3.0.0-git Vetinari (revision 2.2.0-git-14263-g954ec0a4e9)
[089da270] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(process:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
kenn@kenn:~$ 
```

**Comment by cosimoc** [comment] 2017-10-04 18:55
@kensully I wonder if this is an issue for 32-bit platforms, or perhaps the real issue is that locales don't seem to be installed? Can you try to install `org.videolan.VLC.Locale` explicitly and see if that changes anything?

**Comment by kensully** [comment] 2017-10-04 19:29
@cosimoc I tried to install it like `flatpak install --user flathub org.videolan.VLC.Locale` it says it's already installed.

**Comment by kensully** [comment] 2017-10-26 17:22
I cloned this repo and built it via `flatpak-builder  --repo=VLC org.videolan.VLC org.videolan.VLC.json` but the result is the same, it crashes.

**Comment by kensully** [comment] 2017-11-17 10:05
I switched architecture to x86_64  and `VLC` runs well. It appears to be 32 bit support issue.

**Comment by kensully** [comment] 2017-11-17 10:08
I wonder why it complains about `Gtk-Message: Failed to load module "canberra-gtk-module"`, how can I install `canberra-gtk-module` package into flatpak environment?

**Comment by TingPing** [comment] 2017-11-17 22:02
> I wonder why it complains about Gtk-Message: Failed to load module "canberra-gtk-module", how can I install canberra-gtk-module package into flatpak environment?

Some configuration on the host is probably leaking through with the canberra module. As a user there is nothing to do and I don't think we should bundle the module here because it doesn't provide anything useful so its just a harmless warning.

**Comment by kensully** [comment] 2017-11-18 12:35
@TingPing  Thank you for responding, do you know any way to manually install a package into flatpak environment?

**Comment by TingPing** [comment] 2017-11-20 05:45
If I wasn't clear; There is no reason to have that module its not useful.

**Comment by kensully** [comment] 2017-12-17 13:23
This  might be related [core dumped error](https://askubuntu.com/questions/732324/vlc-will-not-launch-15-10l)

I tried the following :  

       $ flatpak run --command=sh org.videolan.VLC 

        sh-4.3$ vlc -I skins2

it launches the `VLC GUI` with the `skin2` but crashes again with `core dumped error` when I click `VLC menu` on the skin.

**Comment by MatMaul** [comment] 2017-12-18 07:44
You can try `flatpak run org.videolan.VLC -vvv` to see if we get more infos.

**Comment by kensully** [comment] 2017-12-18 11:29
@MatMaul thank you for responding. I added debug output to [this gist](https://gist.github.com/kensully/08306690631fa75a971b1259eeda1720)

**Comment by MatMaul** [comment] 2017-12-18 11:36
Ok nothing helpful.
Let's try to get the backtrace:
```
flatpak run --devel --command=sh org.videolan.VLC
gdb vlc
r
```
Then it should segfaults, do a `bt` and paste the output.

**Comment by MatMaul** [comment] 2017-12-18 11:40
oh and install org.videolan.VLC.Debug before doing all of that or the backtrace will be quite a lot less useful ;)

**Comment by kensully** [comment] 2017-12-18 12:36
@MatMaul here it is [vlc debug gist](https://gist.github.com/kensully/16eb142b6a24386402b183376d7f9b41)

**Comment by MatMaul** [comment] 2017-12-18 12:48
I think you didn't do the `bt` at the end.

**Comment by kensully** [comment] 2017-12-18 13:03
@MatMaul  thank you for your help. I am not familiar with `gdb` so missed `bt` step.
[gdb bt](https://gist.github.com/kensully/213985c9562bba2a0890347d68b2aad7)

**Comment by MatMaul** [comment] 2017-12-18 13:08
Did you do the bt right after the crash ? You should see the last line of
the first log (xcb_send_request_with_fds64) in the backtrace.

**Comment by kensully** [comment] 2017-12-18 13:12
Yes, I did. I reran the steps above but only posted `bt` part since I posted it in the previous post.

**Comment by kensully** [comment] 2017-12-18 13:14
maybe this bug related [xcb_send_request_with_fds64](https://github.com/DFHack/stonesense/issues/50)?

**Comment by MatMaul** [comment] 2017-12-18 13:18
Probably not, looks unrelated. no idea for now this backtrace makes no sense, those python errors are weird and seem to have been generated by gdb itself when printing the trace. You did install the Sdk and Debug packages as I mentioned right ?

**Comment by kensully** [comment] 2017-12-18 13:22
Yes, I installed them.

**Comment by kensully** [comment] 2017-12-18 13:40
You are right about it by saying
>those python errors are weird and seem to have been generated by gdb itself when printing the trace
[gdb bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814558)

**Comment by MatMaul** [comment] 2018-12-29 12:31
Please reopen if still not working.

**Closed by MatMaul** 2018-12-29 12:31 UTC
